let scramjet;
let uv;
let scramjetConfigLoaded = false;
let scramjetConfigPromise = null;
let metaPending = null;
let metaFlush = null;
const _inflight = new Map();
const _activePrefetches = new Map();
const _prefetchTimes = new Map();
const _prefetchedResponses = new Map();
const _preloadedLarge = new Map();
const _bandwidthHistory = [];
const _preconnected = new Set();
const _trimmingCaches = new Set();
let adblockDomains = new Set();
let isAdblockReady = false;
let adblockInitPromise = null;
let _lastTransportError = 0;
let _consecutiveProxyFailures = 0;
const _injectPatchCache = new Map();
self.__MOCHI_BASE__ = self.__MOCHI_BASE__ || self.MOCHI_BASE || null;